name: "Quarkus Cron Native image"
on:
  push:
    branches:
      - resteasy-asyncio

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [ 11 ]
    name: build-and-testing
    steps:

      - name: Stop MySQL
        run: sudo systemctl stop mysql

      - name: Pull docker image
        run: docker pull quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java${{ matrix.java }}

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Checkout RESTEasy
        uses: actions/checkout@v2
        with:
          repository: fromage/resteasy
          ref: async-io
          path: resteasy 

      - name: Checkout Quarkus
        uses: actions/checkout@v2
        with:
          repository: fromage/quarkus
          ref: resteasy-asyncio
          path: quarkus

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build RESTEasy
        run: mvn -B install -DskipTests -DskipITs -Dno-format
        working-directory: resteasy

      - name: Build Quarkus
        run: mvn -B install -DskipTests -DskipITs -Dno-format
        working-directory: quarkus

      - name: Run integration tests in native
        run: mvn -B  --settings azure-mvn-settings.xml verify -f integration-tests/pom.xml -DskipTests  -Dno-format -Ddocker -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java${{ matrix.java }} -Dtest-postgresql -Dtest-elasticsearch -Dtest-mysql -Dtest-dynamodb -Dtest-vault -Dtest-neo4j
        working-directory: quarkus
